name: Daily Quote Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Run script
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name "twotnguyen"
          git config --global user.email "nguyenngoctinh011258@gmail.com"
          git add README.md quote.svg profile_dark.svg profile_light.svg cache.json archive.json
          git commit -m "chore: update daily quote and profile stats" || echo "No changes to commit"
          git push
